version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync+restart  # ← Docker перезапустит контейнер при изменениях
          path: ./packages/client/src
          target: /app/packages/client/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: packages/client/package.json
    environment:
      - NODE_ENV=development

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:5173
      - MONGODB_URI=mongo://admin:password@mongo:27017/mydb?authSource=admin
    develop:
      watch:
        - action: sync+restart  # ← Docker перезапустит контейнер при изменениях
          path: ./packages/server/src
          target: /app/packages/server/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: packages/server/package.json
    stdin_open: true
    tty: true
    networks:
      - mongo-net

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    command: [
     "--auth",
     "--bind_ip_all", 
     "--logpath", "/var/log/mongodb/mongod.log",
     "--quiet"  # уменьшаем детализацию логов
    ]
    healthcheck:
      test: |
        timeout 10 bash -c '
          until echo "db.runCommand({ping:1})" | mongosh --quiet --authenticationDatabase admin -u admin -p password localhost:27017/mydb; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
        ' 
    networks:
      - mongo-net
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express-ui
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mongo-net


volumes:
  mongodb_data: 

networks:
  mongo-net:
    driver: bridge
